FROM golang:1

RUN \
  apt-get update && \
  apt-get install apt-transport-https && \
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
  curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
  apt-get install -y nodejs yarn && \
  yarn global add gulp

RUN \
  wget https://raw.githubusercontent.com/pote/gpm/master/bin/gpm && \
  chmod +x gpm && \
  mv gpm /usr/local/bin

WORKDIR /go/src/app
EXPOSE 80
