#!/usr/bin/env bash

# https://stackoverflow.com/questions/7454526
EXEC=( "-c" "pkill gulp; pkill app; pkill node; pkill yarn; bash" )
if [ "$2" = "nokill" ]; then EXEC=( ); fi

docker-compose exec "$1" bash "${EXEC[@]}"
