#!/usr/bin/env bash

docker exec -i "$(docker-compose ps -q postgres)" \
  psql postgres postgres <<EOF
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
EOF

docker exec -i "$(docker-compose ps -q postgres)" psql postgres postgres < "$1"
