#!/usr/bin/env bash

if [ "$1" == "u" ]; then
  gsutil cp .secrets gs://digital-seat-198720/.secrets
elif [ "$1" == "d" ]; then
  gsutil cp gs://digital-seat-198720/.secrets .secrets
else
  echo "Usage: secrets (u | d)"
fi
