#!/usr/bin/env bash

if [ "$1" == "u" ]; then
  gsutil cp .secrets gs://auzom-legacy-jeremejevs/.secrets
elif [ "$1" == "d" ]; then
  gsutil cp gs://auzom-legacy-jeremejevs/.secrets .secrets
else
  echo "Usage: secrets (u | d)"
fi
